"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { useSearchParams } from "next/navigation";
import { toast } from "sonner";
import {
  BookOpen,
  Loader2,
  RefreshCw,
  Copy,
  Check,
  ChevronsUpDown,
  AlertCircle,
  FileText,
  List,
  Building2,
} from "lucide-react";
import {
  Command,
  CommandInput,
  CommandList,
  CommandEmpty,
  CommandGroup,
  CommandItem,
} from "@/components/ui/command";

interface AppOption {
  id: string;
  jobTitle: string;
  company: string;
}

interface StorySections {
  whyMe: string;
  whyThisCompany: string;
  relevantBackground: string;
  whatIHopeToContribute: string;
  howIllMakeAnImpact: string;
}

interface StoryResult {
  detailed: StorySections;
  talkingPoints: StorySections;
}

const SECTION_META: {
  key: keyof StorySections;
  label: string;
  descDetailed: string;
  descTalking: string;
}[] = [
  {
    key: "whyMe",
    label: "Why Me",
    descDetailed: "What makes you uniquely suited for this role",
    descTalking: "Your unique fit in quick talking points",
  },
  {
    key: "whyThisCompany",
    label: "Why This Company",
    descDetailed: "What draws you to their mission, product, and culture",
    descTalking: "Key reasons you're drawn to this company",
  },
  {
    key: "relevantBackground",
    label: "My Relevant Background",
    descDetailed: "Your career arc connected to what this role needs",
    descTalking: "Career highlights that connect to this role",
  },
  {
    key: "whatIHopeToContribute",
    label: "What I Hope to Contribute",
    descDetailed: "Specific ways you can add value",
    descTalking: "Top ways you'll add value",
  },
  {
    key: "howIllMakeAnImpact",
    label: "How I'll Make an Impact",
    descDetailed: "Past work translated to outcomes in this role",
    descTalking: "Past results that translate to this role",
  },
];

type Phase =
  | { type: "idle" }
  | { type: "generating"; message: string }
  | { type: "done" }
  | { type: "error"; error: string };

type ViewTab = "detailed" | "talking";

export default function StoryPage() {
  const searchParams = useSearchParams();
  const preselectedId = searchParams.get("app");

  const [applications, setApplications] = useState<AppOption[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedAppId, setSelectedAppId] = useState<string>("");
  const [phase, setPhase] = useState<Phase>({ type: "idle" });
  const [story, setStory] = useState<StoryResult | null>(null);
  const [editedDetailed, setEditedDetailed] = useState<StorySections | null>(null);
  const [editedTalking, setEditedTalking] = useState<StorySections | null>(null);
  const [copiedDetailed, setCopiedDetailed] = useState(false);
  const [copiedTalking, setCopiedTalking] = useState(false);
  const [activeTab, setActiveTab] = useState<ViewTab>("detailed");
  const [comboboxOpen, setComboboxOpen] = useState(false);
  const comboboxRef = useRef<HTMLDivElement>(null);
  const [storyMeta, setStoryMeta] = useState<{
    jobTitle: string;
    company: string;
  } | null>(null);
  const hasAutoGenerated = useRef(false);

  // Load tracked applications
  useEffect(() => {
    async function load() {
      try {
        const res = await fetch("/api/applications");
        const data = await res.json();
        if (data.success) {
          const apps: AppOption[] = data.data.map(
            (a: { id: string; job: { title: string; company: string } }) => ({
              id: a.id,
              jobTitle: a.job.title,
              company: a.job.company,
            })
          );
          setApplications(apps);
          if (preselectedId && apps.some((a: AppOption) => a.id === preselectedId)) {
            setSelectedAppId(preselectedId);
          }
        }
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [preselectedId]);

  // Auto-generate when preselected
  useEffect(() => {
    if (
      selectedAppId &&
      preselectedId === selectedAppId &&
      !hasAutoGenerated.current &&
      !loading &&
      phase.type === "idle" &&
      !story
    ) {
      hasAutoGenerated.current = true;
      generateStory(selectedAppId);
    }
  }, [selectedAppId, preselectedId, loading, phase.type, story]); // eslint-disable-line react-hooks/exhaustive-deps

  const generateStory = useCallback(
    async (appId?: string) => {
      const id = appId ?? selectedAppId;
      if (!id) return;

      setPhase({ type: "generating", message: "Starting..." });
      setStory(null);
      setEditedDetailed(null);
      setEditedTalking(null);
      setStoryMeta(null);

      try {
        const res = await fetch("/api/story", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ applicationId: id }),
        });

        if (!res.body) throw new Error("No response body");

        const reader = res.body.getReader();
        const decoder = new TextDecoder();
        let buf = "";

        while (true) {
          const { done, value } = await reader.read();
          if (done) break;

          buf += decoder.decode(value, { stream: true });
          const lines = buf.split("\n");
          buf = lines.pop() ?? "";

          for (const line of lines) {
            if (!line.startsWith("data: ")) continue;
            let event;
            try {
              event = JSON.parse(line.slice(6));
            } catch {
              continue;
            }

            if (event.type === "status") {
              setPhase({ type: "generating", message: event.message });
            } else if (event.type === "complete") {
              const result = event.story as StoryResult;
              setStory(result);
              setEditedDetailed(result.detailed);
              setEditedTalking(result.talkingPoints);
              setStoryMeta({
                jobTitle: event.jobTitle,
                company: event.company,
              });
              setPhase({ type: "done" });
            } else if (event.type === "error") {
              setPhase({ type: "error", error: event.error });
            }
          }
        }
      } catch (err) {
        setPhase({
          type: "error",
          error: err instanceof Error ? err.message : "Generation failed",
        });
      }
    },
    [selectedAppId]
  );

  function handleSectionEdit(
    version: ViewTab,
    key: keyof StorySections,
    value: string
  ) {
    if (version === "detailed") {
      setEditedDetailed((prev) => (prev ? { ...prev, [key]: value } : null));
    } else {
      setEditedTalking((prev) => (prev ? { ...prev, [key]: value } : null));
    }
  }

  async function handleCopy(version: ViewTab) {
    const data = version === "detailed" ? editedDetailed : editedTalking;
    if (!data) return;

    const label = version === "detailed" ? "Detailed Version" : "Talking Points";
    const text = SECTION_META.map(
      (s) => `## ${s.label}\n\n${data[s.key]}`
    ).join("\n\n---\n\n");

    await navigator.clipboard.writeText(text);
    if (version === "detailed") {
      setCopiedDetailed(true);
      setTimeout(() => setCopiedDetailed(false), 2000);
    } else {
      setCopiedTalking(true);
      setTimeout(() => setCopiedTalking(false), 2000);
    }
    toast.success(`${label} copied to clipboard`);
  }

  // Close combobox on click outside
  useEffect(() => {
    function handleClick(e: MouseEvent) {
      if (comboboxRef.current && !comboboxRef.current.contains(e.target as Node)) {
        setComboboxOpen(false);
      }
    }
    document.addEventListener("mousedown", handleClick);
    return () => document.removeEventListener("mousedown", handleClick);
  }, []);

  const isGenerating = phase.type === "generating";
  const selectedApp = applications.find((a) => a.id === selectedAppId);
  const currentEdited = activeTab === "detailed" ? editedDetailed : editedTalking;
  const currentCopied = activeTab === "detailed" ? copiedDetailed : copiedTalking;

  return (
    <div className="p-4 md:p-8 max-w-3xl mx-auto">
      {/* Header */}
      <div className="flex items-start justify-between gap-4 mb-8">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center">
            <BookOpen className="w-5 h-5 text-primary" />
          </div>
          <div>
            <h1 className="text-xl font-bold tracking-tight">My Story</h1>
            <p className="text-xs text-muted-foreground mt-0.5">
              AI-crafted narrative tailored to each role
            </p>
          </div>
        </div>
      </div>

      {/* Application selector */}
      <div className="mb-6">
        <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider block mb-2">
          Select an application
        </label>
        <div className="flex gap-2">
          <div ref={comboboxRef} className="relative flex-1">
            <button
              type="button"
              onClick={() => {
                if (!loading && !isGenerating) setComboboxOpen((v) => !v);
              }}
              disabled={loading || isGenerating}
              className="w-full flex items-center justify-between h-10 rounded-lg border border-border bg-card px-3 text-sm font-medium focus:outline-none focus:ring-2 focus:ring-primary/30 disabled:opacity-50 text-left"
            >
              {loading ? (
                <span className="text-muted-foreground">Loading applications...</span>
              ) : selectedApp ? (
                <span className="truncate">
                  <span className="text-foreground">{selectedApp.jobTitle}</span>
                  <span className="text-muted-foreground"> — {selectedApp.company}</span>
                </span>
              ) : (
                <span className="text-muted-foreground">Search for a tracked job...</span>
              )}
              <ChevronsUpDown className="w-4 h-4 shrink-0 text-muted-foreground ml-2" />
            </button>

            {comboboxOpen && (
              <div className="absolute top-full left-0 right-0 mt-1 z-50 rounded-xl border border-border bg-popover shadow-xl overflow-hidden">
                <Command>
                  <CommandInput placeholder="Type to search by company or role..." />
                  <CommandList>
                    <CommandEmpty>No applications found.</CommandEmpty>
                    <CommandGroup>
                      {applications.map((app) => (
                        <CommandItem
                          key={app.id}
                          value={`${app.company} ${app.jobTitle}`}
                          onSelect={() => {
                            setSelectedAppId(app.id);
                            setComboboxOpen(false);
                          }}
                          data-checked={app.id === selectedAppId ? "true" : undefined}
                        >
                          <div className="flex flex-col min-w-0">
                            <span className="text-sm font-medium truncate">{app.jobTitle}</span>
                            <span className="text-xs text-muted-foreground flex items-center gap-1">
                              <Building2 className="w-3 h-3 shrink-0" />
                              {app.company}
                            </span>
                          </div>
                        </CommandItem>
                      ))}
                    </CommandGroup>
                  </CommandList>
                </Command>
              </div>
            )}
          </div>
          <button
            onClick={() => generateStory()}
            disabled={!selectedAppId || isGenerating}
            className="inline-flex items-center gap-2 h-10 px-5 rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 disabled:opacity-50 disabled:pointer-events-none transition-colors shrink-0"
          >
            {isGenerating ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : story ? (
              <RefreshCw className="w-4 h-4" />
            ) : (
              <BookOpen className="w-4 h-4" />
            )}
            {isGenerating
              ? "Generating..."
              : story
              ? "Regenerate"
              : "Generate My Story"}
          </button>
        </div>
      </div>

      {/* Status */}
      {phase.type === "generating" && (
        <div className="rounded-xl border border-border bg-card p-4 mb-6 flex items-center gap-3">
          <div className="relative w-8 h-8 shrink-0">
            <div className="absolute inset-0 rounded-full border-2 border-primary/20" />
            <div className="absolute inset-0 rounded-full border-2 border-t-primary animate-spin" />
            <div className="absolute inset-0 flex items-center justify-center">
              <BookOpen className="w-3.5 h-3.5 text-primary" />
            </div>
          </div>
          <div>
            <p className="text-sm font-medium">{phase.message}</p>
            <p className="text-xs text-muted-foreground">
              This may take 15–30 seconds...
            </p>
          </div>
        </div>
      )}

      {phase.type === "error" && (
        <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-4 mb-6 flex items-start gap-2">
          <AlertCircle className="w-4 h-4 text-destructive shrink-0 mt-0.5" />
          <p className="text-sm text-muted-foreground">{phase.error}</p>
        </div>
      )}

      {/* Story content */}
      {currentEdited && storyMeta && (
        <div>
          {/* Story header + tab toggle */}
          <div className="flex items-center justify-between mb-5">
            <div>
              <h2 className="text-lg font-bold">{storyMeta.jobTitle}</h2>
              <p className="text-sm text-muted-foreground">
                {storyMeta.company}
              </p>
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={() => handleCopy(activeTab)}
                className="inline-flex items-center gap-1.5 h-8 px-3 rounded-md border border-border text-xs font-medium text-muted-foreground hover:text-foreground hover:bg-white/5 transition-colors"
              >
                {currentCopied ? (
                  <Check className="w-3.5 h-3.5 text-green-400" />
                ) : (
                  <Copy className="w-3.5 h-3.5" />
                )}
                {currentCopied ? "Copied" : "Copy All"}
              </button>
              <button
                onClick={() => generateStory()}
                disabled={isGenerating}
                className="inline-flex items-center gap-1.5 h-8 px-3 rounded-md border border-border text-xs font-medium text-muted-foreground hover:text-foreground hover:bg-white/5 transition-colors disabled:opacity-50"
              >
                <RefreshCw
                  className={`w-3.5 h-3.5 ${isGenerating ? "animate-spin" : ""}`}
                />
                Regenerate
              </button>
            </div>
          </div>

          {/* Tab toggle */}
          <div className="flex rounded-lg border border-border overflow-hidden mb-5">
            <button
              onClick={() => setActiveTab("detailed")}
              className={`flex-1 flex items-center justify-center gap-2 px-4 py-2.5 text-sm font-medium transition-colors ${
                activeTab === "detailed"
                  ? "bg-primary text-primary-foreground"
                  : "text-muted-foreground hover:text-foreground hover:bg-white/5"
              }`}
            >
              <FileText className="w-4 h-4" />
              Detailed Version
            </button>
            <button
              onClick={() => setActiveTab("talking")}
              className={`flex-1 flex items-center justify-center gap-2 px-4 py-2.5 text-sm font-medium transition-colors ${
                activeTab === "talking"
                  ? "bg-primary text-primary-foreground"
                  : "text-muted-foreground hover:text-foreground hover:bg-white/5"
              }`}
            >
              <List className="w-4 h-4" />
              Talking Points
            </button>
          </div>

          {/* Tab description */}
          <p className="text-xs text-muted-foreground mb-5">
            {activeTab === "detailed"
              ? "Full narrative for cover letters and deep interview prep. Edit any section to make it yours."
              : "Concise bullet points to review in 5 minutes before walking into an interview."}
          </p>

          {/* Sections */}
          <div className="space-y-5">
            {SECTION_META.map((meta, i) => (
              <div
                key={meta.key}
                className="rounded-xl border border-border bg-card overflow-hidden"
              >
                <div className="px-5 py-3 border-b border-border/50 bg-white/[0.02]">
                  <div className="flex items-baseline gap-2">
                    <span className="text-xs font-bold text-primary/60">
                      {i + 1}
                    </span>
                    <h3 className="text-sm font-semibold">{meta.label}</h3>
                  </div>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    {activeTab === "detailed"
                      ? meta.descDetailed
                      : meta.descTalking}
                  </p>
                </div>
                <textarea
                  value={currentEdited[meta.key]}
                  onChange={(e) =>
                    handleSectionEdit(activeTab, meta.key, e.target.value)
                  }
                  className="w-full bg-transparent px-5 py-4 text-sm leading-relaxed resize-none focus:outline-none min-h-[80px]"
                  rows={Math.max(
                    activeTab === "talking" ? 3 : 5,
                    currentEdited[meta.key].split("\n").length + 1
                  )}
                />
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Empty state */}
      {!story && phase.type === "idle" && (
        <div className="rounded-xl border border-dashed border-border p-12 text-center">
          <BookOpen className="w-10 h-10 text-muted-foreground/30 mx-auto mb-3" />
          <p className="text-sm font-medium">No story generated yet</p>
          <p className="text-xs text-muted-foreground mt-1">
            {applications.length > 0
              ? "Select a tracked application and generate your personalized narrative"
              : "Track some applications first, then come back to generate your story"}
          </p>
        </div>
      )}
    </div>
  );
}
